'use-client'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { MainLayout } from '@/components/layout'
import { NextPageWithLayout } from '../models'
const Home: NextPageWithLayout = () => {
  const router = useRouter()
  function goToDetailPage() {
    router.push({
      pathname: 'post/[postId]',
      query: {
        postId: 123, // path param
        ref: 'social' // query param url.com/path?...
      }
    })
  }
  return (
    <div>
      <div className={styles.container}>
        <Head>
          <title>Demo Nextjs</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{' '}
            <code className={styles.code}>pages/index.js</code>
          </p>
          <Link href="/about" >
            <p >Go to about</p>
          </Link>

          <button onClick={goToDetailPage}>Go to post detail</button>

          <div className={styles.grid}>
            <div className='bg-black'>
              <div className="box-of-star1">
                <div className="star star-position1" />
                <div className="star star-position2" />
                <div className="star star-position3" />
                <div className="star star-position4" />
                <div className="star star-position5" />
                <div className="star star-position6" />
                <div className="star star-position7" />
              </div>
              <div className="box-of-star2">
                <div className="star star-position1" />
                <div className="star star-position2" />
                <div className="star star-position3" />
                <div className="star star-position4" />
                <div className="star star-position5" />
                <div className="star star-position6" />
                <div className="star star-position7" />
              </div>
              <div className="box-of-star3">
                <div className="star star-position1" />
                <div className="star star-position2" />
                <div className="star star-position3" />
                <div className="star star-position4" />
                <div className="star star-position5" />
                <div className="star star-position6" />
                <div className="star star-position7" />
              </div>
              <div className="box-of-star4">
                <div className="star star-position1" />
                <div className="star star-position2" />
                <div className="star star-position3" />
                <div className="star star-position4" />
                <div className="star star-position5" />
                <div className="star star-position6" />
                <div className="star star-position7" />
              </div>
              <div data-js="astro" className="astronaut">
                <div className="head" />
                <div className="arm arm-left" />
                <div className="arm arm-right" />
                <div className="body">
                  <div className="panel" />
                </div>
                <div className="leg leg-left" />
                <div className="leg leg-right" />
                <div className="schoolbag" />
              </div>
            </div>

          </div>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </div>
  )
}

Home.Layout = MainLayout

export default Home
